goccy/kubetest

api/v1/testjob_runner.go
In the distributed test, the command is the same except for the environment variables, so the key is the same ....
=> Fix getting of failed test commands

api/v1/testjob_runner.go
If doesn't set `workingDir` to test container and use git checkout , set checkout directory to workingDir of test container .
=> Fix WorkingDir

api/v1/testjob_runner.go
We encounter error at merge process 
```
*** Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: unable to auto-detect email address (got 'None.(none)')
```
So, we run `git config user.email anonymous@kubetest.com` and `git config user.name anonymous` before merge
=> Fix merge process

api/v1/testjob_runner.go, go.mod
- Add `kubetest.io/listjob=true` label for list job .
- Add `kubetest.io/testjob=true` label for test job .
- Add `kubetest.io/tests` annotation for showing all test cases .
=> Add metadata

api/v1/testjob_runner.go, cmd/kubetest/main.go, go.mod, testdata/config/manifest.yaml
- Support verbose(debug) logging
- Added validation for test logs 
- Fix permissions for pods
=> Support verbose(debug) log and validate test logs

.github/workflows/test.yaml, Makefile, README.md, api/v1/testjob_runner.go, cmd/kubetest/main.go, go.mod, kubetest_test.go, testdata/config/manifest.yaml
Also, added CI with coverage and some debug logs .
Bump up kubejob version to v0.1.0 .
Changes: https://github.com/goccy/kubejob/pull/7
=> Add Signal Handler ( SIGINT / SIGTERM )

api/v1/kubetest_test.go, api/v1/testjob_runner.go
=> Add test cases for improvement coverage 

api/v1/testjob_runner.go
=> Add error status as the testResult param

api/v1/kubetest_test.go
Add test cases for prepare steps and simple running test case.
=> Improve coverage

codecov.yaml
=> Ignore generated file for measuring coverage

api/v1/testjob_api.go
=> Copy default test container

api/v1/testjob_runner.go
Example
```
TEST=Test_A: go test -v ./ -run $TEST
=== RUN   Test_A
go_test.go:9: Test A
--- PASS: Test_A (1.01s)
PASS
ok      github.com/goccy/kubetest/_examples     1.458s
elapsed time: 95sec (current time: 2021-03-16T10:17:37Z)
1/14 (7.142858%) finished.
```
=> Add elapsed time and test count information to report log

api/v1/testjob_runner.go
=> Fix race condition for testCount

Makefile, cmd/kubetest/main.go, cmd/kubetest/main_test.go
Skip empty or whitespace only line on list file
=> Fix list option

api/v1/kubetest_test.go, api/v1/testjob_api.go, api/v1/testjob_copyfile.go, api/v1/testjob_runner.go
Use a simple `cat` based file copy. Also, output the debug log when copying.
=> Fix copying artifact

api/v1/logger.go, api/v1/mask_test.go, api/v1/testjob_runner.go
Mask all logs to print to console
=> Mask secret keyword to print to console

api/v1/testjob_runner.go, go.mod, go.sum
https://github.com/goccy/kubejob/compare/v0.2.5...v0.2.6
=> Output command log at error for prepare command

api/v1/testjob_api.go, api/v1/testjob_runner.go
Also, output command log at error for list
=> Ignore empty name as a target of testing list

api/v1/job.go, api/v1/runner_test.go, api/v1/subtask.go, api/v1/task.go, api/v1/task_builder.go, go.mod, go.sum
- Update kubejob to v0.2.11
- Fix error handling for mount step
- Care long pending phase of Pod
=> Fix error handling for mount step

api/v1/repo_test.go, api/v1/validator.go
=> Fix validation error for clonedPath of repository spec

api/v1/runner_test.go, api/v1/task_builder.go
An error occurs when volumeMounts does not specify the volume that exists in volumes .
=> Fix volume mount logic

api/v1/scheduler.go, api/v1/scheduler_test.go, api/v1/validator.go
- Add validation for scheduled task num
- Add validation for `maxConcurrentNumPerPod` and `maxContainersPerPod`
- Add test cases for scheduler
=> Fix scheduling for task

api/v1/runner_test.go, api/v1/scheduler.go
If an error occurs when getting the dynamic key, it will immediately end with an error.
=> Fix getting of dynamic keys

api/v1/runner.go, api/v1/subtask.go, api/v1/task.go, api/v1/types.go, cmd/kubetest/main.go
=> Export Report type

api/v1/task_builder.go
First copy the template spec to apply destructive changes to the ContainerSpec for volumeMount processing
=> Fix to be idempotent when retrying task

go.mod, go.sum
Apply https://github.com/goccy/kubejob/compare/v0.3.1...v0.3.2
=> Update kubejob version to v0.3.2

api/v1/job.go, api/v1/subtask.go, api/v1/task.go, api/v1/task_builder.go, go.mod, go.sum
- Extend default timeout to 10 minutes
- Add error case for retry
- Add debug information
- Fix copy process by kubejob
=> Fix retry process

api/v1/repo.go
=> Fix archiving process of symlink file
